### PR TITLE
cmd/root: Search subordinate ID files for also the UID

### LINKED ISSUE #954: Toolbox should search /etc/subuid for both the username and UID
**Describe the bug**
According to the [subuid man page](https://man.archlinux.org/man/core/shadow/subuid.5.en), the `/etc/subuid` and `/etc/subgid` files can either contain usernames or UIDs. It looks like Toolbox only checks if the username is in the file, not both the username and UID. Consequently, that causes `toolbox` commands to fail when `/etc/subuid` only contains UIDs. However, `podman` commands still work fine.
```
toolbox create --log-level debug
DEBU Running as real user ID 1000                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user ta180m 
DEBU Validating sub-ID file /etc/subuid           
Error: /etc/subgid and /etc/subuid don't have entries for user ta180m
See the podman(1), subgid(5), subuid(5) and usermod(8) manuals for more
information.
```
```
cat /etc/subuid
1000:100000000:65536
1001:100100000:65536
1002:100200000:65536
1003:100300000:65536
1004:100400000:65536
1005:100500000:65536
1006:100600000:65536
1007:100700000:65536
1008:100800000:65536
1009:100900000:65536
1010:101000000:65536
```

**Steps how to reproduce the behaviour**
1. Edit the `/etc/subuid` and `/etc/subgid` files to look like above.
2. Run `toolbox` commands.

**Expected behaviour**
`toolbox` shouldn't complain since the UID is in the `/etc/subuid` and `/etc/subgid` files.

**Actual behaviour**
`toolbox` doesn't work while `podman` commands work fine.

**Output of `toolbox --version` (v0.0.90+)**
`toolbox version 0.0.99.2`

**Toolbox package info (`rpm -q toolbox`)**
```
Name            : toolbox
Version         : 0.0.99.2-1
Description     : Unprivileged development environment
Architecture    : x86_64
URL             : https://github.com/containers/toolbox
Licenses        : APACHE
Groups          : None
Provides        : None
Depends On      : podman  bash  flatpak
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 5.61 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Mon 28 Jun 2021 04:11:18 AM CDT
Install Date    : Thu 09 Dec 2021 05:13:59 PM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Output of `podman version`**
```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.4
Git Commit:   f6526ada1025c2e3f88745ba83b8b461ca659933
Built:        Thu Dec  9 12:30:40 2021
OS/Arch:      linux/amd64
```

**Podman package info (`rpm -q podman`)**
```
Name            : podman
Version         : 3.4.4-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/podman
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  crun  fuse-overlayfs  iptables
                  libdevmapper.so=1.02-64  libgpgme.so=11-64  libseccomp.so=2-64  slirp4netns
Optional Deps   : apparmor: for AppArmor support
                  btrfs-progs: support btrfs backend devices [installed]
                  catatonit: --init flag support
                  podman-docker: for Docker-compatible CLI
Required By     : cockpit-podman  podman-compose  toolbox
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 72.79 MiB
Packager        : David Runge <dvzrv@archlinux.org>
Build Date      : Thu 09 Dec 2021 12:30:40 PM CST
Install Date    : Fri 10 Dec 2021 07:22:21 PM CST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Info about your OS**
Arch Linux

### PR DESCRIPTION
**Pull request by Ta180m**
... and not just the username.

https://github.com/containers/toolbox/issues/954

### CODE REVIEW

File: src/cmd/root.go [hunk 1]
```diff
@@ -382,12 +382,12 @@ func validateSubIDFile(path string) (bool, error) {
 	scanner := bufio.NewScanner(file)
 	scanner.Split(bufio.ScanLines)
 
-	prefix := currentUser.Username + ":"
-
 	for scanner.Scan() {
 		line := scanner.Text()
-		if strings.HasPrefix(line, prefix) {
-			return true, nil
+		for _, prefix := range [2]string{currentUser.Username + ":", currentUser.Uid + ":"} {
```
Comment (debarshiray) [inline src/cmd/root.go:387]: Nitpick: will be slightly more readable to split the slice of prefixes into a separate line.

**Review by debarshiray — COMMENTED** [review]
Thanks for the patch!

**Comment by debarshiray** [comment]
recheck

**Comment by debarshiray** [comment]
I have no idea what's wrong with the CI now.  I am going to assume that this is a Software Factory / Zuul problem because the CI is passing for this [other PR](https://github.com/containers/toolbox/pull/963) which includes these patches and adds some documentation changes on top.

**Comment by debarshiray** [comment]
I took the liberty to make the above changes, and tweaked the commit message to link to https://github.com/containers/toolbox/issues/954

Thanks for your contribution, @Ta180m
