### PR TITLE
cmd/initContainer: Remove path on redirection when it exists

### LINKED ISSUE #539: can't enter fedora 33 containers: Error: failed to redirect /media to /run/media
```
[bam@host ~]$ toolbox --verbose  enter --container kde.f33
DEBU Running as real user ID 1001                 
DEBU Resolved absolute path to the executable as /usr/bin/toolbox 
DEBU Running on a cgroups v2 host                 
DEBU Checking if /etc/subgid and /etc/subuid have entries for user bam 
DEBU TOOLBOX_PATH is /usr/bin/toolbox             
DEBU Toolbox config directory is /home/bam/.config/toolbox 
DEBU Current Podman version is 2.0.4              
DEBU Old Podman version is 2.0.4                  
DEBU Migration not needed: Podman version 2.0.4 is unchanged 
DEBU Resolving container and image names          
DEBU Container: 'kde.f33'                         
DEBU Image: ''                                    
DEBU Release: ''                                  
DEBU Resolved container and image names           
DEBU Container: 'kde.f33'                         
DEBU Image: 'fedora-toolbox:32'                   
DEBU Release: '32'                                
DEBU Checking if container kde.f33 exists         
DEBU Calling org.freedesktop.Flatpak.SessionHelper.RequestSession 
DEBU Starting container kde.f33                   
DEBU Inspecting entry point of container kde.f33  
DEBU Entry point PID is a float64                 
DEBU Entry point of container kde.f33 is toolbox (PID=0) 
Error: invalid entry point PID of container kde.f33
```
```
[bam@host ~]$ toolbox --version
toolbox version 0.0.93

[bam@host ~]$ podman start --attach kde.f33
level=debug msg="Running as real user ID 0"
level=debug msg="Resolved absolute path to the executable as /usr/bin/toolbox"
level=debug msg="TOOLBOX_PATH is /usr/bin/toolbox"
level=debug msg="XDG_RUNTIME_DIR is unset"
level=debug msg="XDG_RUNTIME_DIR set to /run/user/1001"
level=debug msg="Creating /run/.toolboxenv"
level=debug msg="Monitoring host"
level=debug msg="Path /run/host/etc exists"
level=debug msg="Binding /etc/machine-id to /run/host/etc/machine-id"
level=debug msg="Creating /run/systemd/journal"
level=debug msg="Binding /run/systemd/journal to /run/host/run/systemd/journal"
level=debug msg="Creating /var/lib/flatpak"
level=debug msg="Binding /var/lib/flatpak to /run/host/var/lib/flatpak"
level=debug msg="Creating /var/log/journal"
level=debug msg="Binding /var/log/journal to /run/host/var/log/journal"
level=debug msg="Creating /var/mnt"
level=debug msg="Binding /var/mnt to /run/host/var/mnt"
level=debug msg="Creating /sys/fs/selinux"
level=debug msg="Binding /sys/fs/selinux to /usr/share/empty"
level=debug msg="Path /run/host/monitor exists"
level=debug msg="Redirecting /media to /run/media"
Error: failed to redirect /media to /run/media
```

I don't see that `/media` line at all when attaching to f32 container:
```
[bam@host ~]$ podman --log-level debug start --attach kde.f32
....                    
level=debug msg="Running as real user ID 0"
level=debug msg="Resolved absolute path to the executable as /usr/bin/toolbox"
level=debug msg="TOOLBOX_PATH is /usr/bin/toolbox"
level=debug msg="XDG_RUNTIME_DIR is unset"
level=debug msg="XDG_RUNTIME_DIR set to /run/user/1001"
level=debug msg="Creating /run/.toolboxenv"
level=debug msg="Monitoring host"
level=debug msg="Path /run/host/etc exists"
level=debug msg="Binding /etc/machine-id to /run/host/etc/machine-id"
level=debug msg="Creating /run/systemd/journal"
level=debug msg="Binding /run/systemd/journal to /run/host/run/systemd/journal"
level=debug msg="Creating /var/lib/flatpak"
level=debug msg="Binding /var/lib/flatpak to /run/host/var/lib/flatpak"
level=debug msg="Creating /var/log/journal"
level=debug msg="Binding /var/log/journal to /run/host/var/log/journal"
level=debug msg="Creating /var/mnt"
level=debug msg="Binding /var/mnt to /run/host/var/mnt"
level=debug msg="Creating /sys/fs/selinux"
level=debug msg="Binding /sys/fs/selinux to /usr/share/empty"
level=debug msg="Path /run/host/monitor exists"
level=debug msg="Finished initializing container"
level=debug msg="Creating runtime directory /run/user/1001/toolbox"
level=debug msg="Creating initialization stamp /run/user/1001/toolbox/container-initialized-17636"
level=debug msg="Going to sleep"
DEBU[0137] Sending signal 28 to container 3cda239851f1cb2706cc312490e6b75b568eb1e1f92c56f52bd1ea924674d547 
```

### PR DESCRIPTION
**Pull request by HarryMichal**
The `redirectPath()` function does not work correctly if `containerPath`
does not exist (like `/media`). The error message often looks like this:

```
Error: failed to redirect /media to /run/media: remove /media: no such file or directory
```

This makes `redirectPath` try to remove `containerPath` only if it exists.
The existence of `containerPath` is checked using `utils.PathExist()`.

Fixes #539

### CODE REVIEW

File: src/cmd/initContainer.go [hunk 1]
```diff
@@ -494,12 +494,14 @@ func redirectPath(containerPath, target string, folder bool) error {
 	logrus.Debugf("Preparing to redirect %s to %s", containerPath, target)
 	targetSanitized := sanitizeRedirectionTarget(target)
 
-	err := os.Remove(containerPath)
-	if folder {
-		if err != nil {
+	if utils.PathExists(containerPath) {
+		err := os.Remove(containerPath)
```
Comment (debarshiray) [inline src/cmd/initContainer.go:498]: File system operations are inherently racy. In theory, some other process could have removed `containerPath` between the `utils.PathExists` and `os.Remove` calls. It's unlikely, but possible.

Therefore, if possible, it's better to proceed with the actual operation and handle any errors coming out from it. In this case, we'd use `os.IsNotExist` on the error.

**Review by debarshiray — CHANGES_REQUESTED** [review]
Thanks for working on this!

File: src/cmd/initContainer.go (hunk 1 above)
Comment (debarshiray) [reply src/cmd/initContainer.go]: I took the liberty to tweak it as above.
